### PR TITLE
Add flake.nix

### PR DESCRIPTION
**Pull request by purefunctor**

### CODE REVIEW

**Comment by f-f** [comment]
Is there a reason for moving to flakes? I am using `lorri`, which does not work with flakes yet, but works with a traditional nix-shell.

**Comment by purefunctor** [comment]
If anything, I just like `nix develop` over `nix-shell` 😄—I haven't used Nix in a while so I wasn't aware that lorri doesn't work as consistently with flakes.

**Comment by f-f** [comment]
I personally prefer flakes too, but this lorri issue has prevented me from switching more repos.
I'm having trouble with it anyways lately, let me see if I can switch to something else

**Comment by purefunctor** [comment]
I'm currently using `nix-direnv` for my WSL setup and it works decently well with Emacs and VS Code. I've yet to try it on flakes though but I think it supports it concretely?

**Review by f-f — APPROVED** [review]

**Pull request merged**
