### PR TITLE
Speed up curried app printing

### PR DESCRIPTION
**Pull request by JordanMartinez**
Remove unneeded `uncons`ing

I noticed this while working on #98. Depends on #98.

### CODE REVIEW

**Review by turlando — COMMENTED** [review]
I just realized that this function does not print a curried application, but a curried lambda... maybe we should change its name?

**Comment by turlando** [comment]
Is this ready to be reviewed?

**Comment by JordanMartinez** [comment]
Oh! This is still in draft. Ha! :sweat_smile:

**Comment by JordanMartinez** [comment]
Actually, it's not in draft.

Yes, this is ready for review.

**Comment by turlando** [comment]
Sorry, I was asking because I've seen you were still committing to this branch :)

**Pull request merged**
