### PR TITLE
Major and minor refactorings

### PR DESCRIPTION
**Pull request by purefunctor**
We should probably do a merge commit for this to preserve history?

### CODE REVIEW

**Comment by JordanMartinez** [comment]
> * Move common forms to Common.purs

Why make the above change in your first commit? I don't understand why this should be done and without knowing that, it just seems like a pointless change to me.

**Comment by purefunctor** [comment]
> > * Move common forms to Common.purs
> 
> Why make the above change in your first commit? I don't understand why this should be done and without knowing that, it just seems like a pointless change to me.

I was thinking of also moving the `scmPrefixed` values into the `Constants` file, where they would also be wrapped in `Identifier`. The dependency tree would look like:
```
Syntax -> Constants -> Common
Syntax -> Common
```

**Comment by f-f** [comment]
@purefunctor if these refactorings are unrelated it might be worth to have each be in their own pull request, so they can have separate discussions

**Comment by f-f** [comment]
@purefunctor is it worth to bring this up to date, or should we close it?

**Comment by purefunctor** [comment]
I think this should be closed, I'll re-open PRs over time for the changes here.

**Pull request closed without merging**
