### PR TITLE
Add control, invariant, maybe to the package-set

### PR DESCRIPTION
**Pull request by anttih**

### CODE REVIEW

**Comment by anttih** [comment]
Should we also add these as dependencies to the test suite just to check that the package-set compiles?

**Comment by f-f** [comment]
> Should we also add these as dependencies to the test suite just to check that the package-set compiles?

Ah yes, great idea

**Comment by anttih** [comment]
Actually I can't do that in this PR yet. Waiting for the new spago for that.

**Comment by anttih** [comment]
I'd like to merge this, I need it for other package updates. I can add the test deps later.

**Review by f-f — APPROVED** [review]

**Pull request merged**
