### PR TITLE
Update console, compile all packages in tests

### PR DESCRIPTION
**Pull request by anttih**

### CODE REVIEW

**Review by f-f — APPROVED** [review]

**Comment by f-f** [comment]
This is good - I just released `0.93.15` that has the fix for local package sets, but Nix doesn't want to build it (see https://github.com/thomashoneyman/purescript-overlay/issues/47), so we can't have it in CI here yet

**Comment by f-f** [comment]
@anttih until we ship this with Nix maybe you can use it locally to check that the new package set works with the test project before putting the remote URL there

**Comment by anttih** [comment]
> @anttih until we ship this with Nix maybe you can use it locally to check that the new package set works with the test project before putting the remote URL there

Not sure I understand.

**Comment by f-f** [comment]
Nevermind, I'll sort this nix thing out 😄

**Pull request merged**
